# Force dep to vendor the code generators, which aren't imported just used at dev time.
[[override]]
  name = "k8s.io/api"
  branch = "master"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "master"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.0-alpha.0"

